apiVersion: v1
kind: Pod
metadata:
  name: opa-allowed
  namespace: secure
spec:
  containers:
    - name: opa
      image: openpolicyagent/opa:0.9.2
---
apiVersion: v1
kind: Pod
metadata:
  name: opa-not-allowed
  namespace: secure
spec:
  containers:
    - name: nginx
      image: nginx:latest
