apiVersion: v1
kind: Pod
metadata:
  name: security-ctx-demo
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    runAsNonRoot: true
  #seccompProfile:
  #  ...
  #appArmorProfile:
  #  ...
  containers:
    - name: sec-ctx-demo
      image: busybox:1.28
      command: [ "sh", "-c", "sleep 1h" ]
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
        capabilities:
          add: []
        privileged: false
