apiVersion: audit.k8s.io/v1
kind: Policy
omitStages:
  - "RequestReceived"
rules:
  - level: RequestResponse
    verbs: ["list"]
    resources:
    - group: ""
      resources: ["pods"]
    namespaces: ["kube-system"]
  # A catch-all rule to log all other requests at the Metadata level.
  - level: Metadata
