apiVersion: v1
data:
  default.conf: |
    server {
        listen 8080

        server_name localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-secure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8080
        env:
        - name: NGINX_PORT
          value: "8080"  # Definir el puerto como variable de entorno
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: cache
          mountPath: /var/cache/nginx
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 3000
          runAsUser: 1000
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config  # Usamos el ConfigMap para cargar el archivo nginx.conf
      - name: cache
        emptyDir: {}
