apiVersion: v1
kind: Pod
metadata:
  name: backend-pod-with-env
spec:
  containers:
    - image: nginx
      name: backend
      env:
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: password
---
apiVersion: v1
kind: Pod
metadata:
  name: backend-pod-with-mount
spec:
  volumes:
    - name: db-creds
      secret:
        secretName: db-creds
  containers:
    - image: nginx
      name: backend
      volumeMounts:
      - name: db-creds
        mountPath: /etc/db-creds
        readOnly: true
