apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: kubesec-demo-sa
---
apiVersion: v1
kind: Pod
metadata:
  name: kubesec-demo
  annotations:
    test: test
    container.seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
    container.apparmor.security.beta.kubernetes.io/nginx: "runtime/default"
spec:
  serviceAccountName: kubesec-demo-sa
  serviceAccount: kubesec-demo-sa
  automountServiceAccountToken: false
  securityContext:
    runAsGroup: 10001
    runAsUser: 10001
    seccompProfile:
      type: Localhost
      localhostProfile: profiles/violation.json
  containers:
    - name: kubesec-demo
      image: gcr.io/google-samples/node-hello:1.0
      resources:
        limits:
          cpu: !!str 1
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 512Mi
      securityContext:
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
